config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts, only: [:new, :create, :index]
  root "posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 10, maximum: 50 }
  validates :body, presence: true, length: { maximum: 500 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false }

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false }

  validates :email, presence: true

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 3).order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Members</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "main" %>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark position-fixed w-100 fixed-top">
      <a class="navbar-brand" href="#">
         <%= image_tag "members.png", width: "40" %>
    </a>
      <h2 class="text-white ">Secret Society</h2>
      <button class="navbar-toggler" type="button<" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <form class="form-inline my-2 my-lg-0 ml-auto">

          <% if user_signed_in? %>
          <%= link_to 'logOut', destroy_user_session_path, method: :delete, class:"mr-3 bg-danger text-white px-2 py-1 radius" %>
           <% else %>
          <%= link_to "Log in", new_user_session_path, class:"mr-3 bg-primary text-white px-2 py-1 radius" %>
          <%= link_to "Sign up", new_user_registration_path, class:"mr-3 bg-success text-white px-2 py-1 radius"  %>
           <% end %>

        </form>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/posts/_card.html.erb
<% @posts.each do |post| %>
<div class="card text-left mt-2">
  <div class="card-header bg-secondary text-white">
  <% if user_signed_in? %>
  <h5><%= post.user.name %></h5>
  <% else %>
  <h5>Annoynymous</h5>
  <% end %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= post.title %></h5>
    <% if user_signed_in? %>
    <hr>
    <p class="card-text"><%= post.body %></p>
    <% end %>
  </div>
  <div class="card-footer text-muted">
    <% if user_signed_in? %>
    <p>Created at: <%= post.user.created_at %></p>
    <% else %>
    <%= link_to "Sign up or Log In to see all the secrets", new_user_registration_path, class:"mr-3 bg-success text-white px-2 py-1 radius"  %>
    <% end %>
  </div>
</div>
<% end %>

app/views/posts/_form.html.erb
<div class="row justify-content-center form-cont overflow-hidden">
  <div class="w-50 pb-5 overflow-hidden">

    <%= form_with(model: post, local: true) do |form| %>

    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="card">
        <div class="card-header p-0">
            <div class="bg-info text-white text-center py-2">
                <i class="fas fa-paper-plane fa-2x"></i>
            </div>
        </div>
        <div class="card-body overflow-hidden p-3">

            <!--Body-->
            <div class="form-group overflow-hidden">
                <div class="input-group mb-2">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-heading text-info"></i></i></div>
                    </div>
                        <%= form.text_field :title, class:"form-control",id:"title",placeholder:"Title"%>
                </div>
            </div>

            <div class="form-group overflow-hidden">
                <div class="input-group mb-2">
                    <div class="input-group-prepend">
                        <div class="input-group-text"><i class="fas fa-keyboard text-info"></i></i></div>
                    </div>
                      <%= form.text_area :body,class:"form-control",placeholder:"Write your post here", rows:"5" %>
                </div>
            </div>

            <div class="text-center overflow-hidden">
                <%= form.submit "Submit",class:"btn btn-info btn-block rounded-0 py-2" %>
            </div>
        </div>

    </div>

    <% end %>

  </div>
</div>

app/views/posts/index.html.erb
<p id="notice"class="text-center my-2 text-danger py-2 font-weight-bold"><%= notice %></p>

<div class="container w-75 position-relative">

<div class="titlecont bg-info d-flex px-2 py-2">
<% if user_signed_in? %>
<h3 class="text-white py-2">All the secrets of members</h3>
<% else %>
<h3 class="text-white py-2">Log In or Sign Up to see all the secrets in details</h3>
<% end %>
<%= link_to '+ New Post', new_post_path,class:"btn-danger px-3 py-2 ml-auto align-self-center new" %>
</div>

<%= render 'card', post: @post %>

<div align="center" class= "apple_pagination">
  <%= will_paginate @posts %>
</div>

<br>
</div>

app/views/posts/new.html.erb
<div class="container">

<h1  class="bg-secondary col-12 col-md-5 col-lg-5 py-2 my-4 mx-auto text-center text-white">New Post</h1>

<%= render 'form', post: @post %>

<div class="container text-center">
<%= link_to 'Back', posts_path, class:"bg-secondary text-white px-3 py-2 radius" %>
</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name),class:"mr-3 bg-info btn-block text-white px-2 py-1 w-25 text-center" %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>